const CART_KEY="pearl_cart_v2";
const getCart=()=>{try{return JSON.parse(localStorage.getItem(CART_KEY))||[]}catch(e){return[]}};
function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));updateCartCount()}
function addToCart(id,quantity=1,size="",color=""){const p=getProduct(id);if(!p)return;const c=getCart(),key=`${id}|${size||p.sizes[0]}|${color||p.colors[0]}`,x=c.find(i=>i.key===key);if(x)x.quantity+=quantity;else c.push({key,id,quantity,size:size||p.sizes[0],color:color||p.colors[0]});saveCart(c);toast("Article ajouté au panier")}
function removeFromCart(key){saveCart(getCart().filter(x=>x.key!==key));renderCart()}
function changeQuantity(key,d){const c=getCart(),x=c.find(i=>i.key===key);if(!x)return;x.quantity+=d;if(x.quantity<1)return removeFromCart(key);saveCart(c);renderCart()}
function details(){return getCart().map(x=>({...x,product:getProduct(x.id)})).filter(x=>x.product)}
function subtotal(){return details().reduce((s,x)=>s+x.product.price*x.quantity,0)}
function updateCartCount(){document.querySelectorAll("[data-cart-count]").forEach(e=>e.textContent=getCart().reduce((s,x)=>s+x.quantity,0))}
function toast(t){let e=document.querySelector(".toast");if(!e){e=document.createElement("div");e.className="toast";e.style.cssText="position:fixed;right:20px;bottom:20px;background:#171513;color:#fff;padding:14px 18px;z-index:99";document.body.appendChild(e)}e.textContent=t;e.style.display="block";clearTimeout(window._t);window._t=setTimeout(()=>e.style.display="none",2000)}
function renderCart(){const b=document.querySelector("[data-cart-items]"),s=document.querySelector("[data-cart-summary]");if(!b)return;const a=details();if(!a.length){b.innerHTML='<div class="empty"><h2>Votre panier est vide</h2><p>Découvrez la sélection PEARL.</p><a class="btn" href="boutique.html">Découvrir la boutique</a></div>';if(s)s.innerHTML="";return}b.innerHTML=a.map(x=>`<div class="cart-item"><div class="cart-thumb"><img src="${x.product.image}" alt="${x.product.name}"></div><div><div class="product-meta">${x.product.category}</div><h3>${x.product.name}</h3><small>${x.size} · ${x.color}</small><div class="quantity" style="margin-top:9px"><button onclick="changeQuantity('${x.key}',-1)">−</button><span>${x.quantity}</span><button onclick="changeQuantity('${x.key}',1)">+</button></div></div><div><strong>${formatPrice(x.product.price*x.quantity)}</strong><br><button class="filter" onclick="removeFromCart('${x.key}')">Supprimer</button></div></div>`).join("");if(s)s.innerHTML=`<h3>Résumé</h3><div class="summary-line"><span>Sous-total</span><strong>${formatPrice(subtotal())}</strong></div><div class="summary-line"><span>Livraison</span><span>À confirmer</span></div><div class="summary-line total"><span>Total</span><span>${formatPrice(subtotal())}</span></div><a class="btn gold" style="width:100%;margin-top:12px" href="contact.html?checkout=1">Commander</a>`}
document.addEventListener("DOMContentLoaded",()=>{updateCartCount();renderCart()});
